module.exports = {
  BOX_TYPES: ['SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE'],

  USER_ROLES: { USER: 'USER', ADMIN: 'ADMIN' },

  ORDER_STATUSES: {
    RESERVED: 'RESERVED',
    READY_FOR_PICKUP: 'READY_FOR_PICKUP',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
    BOX_NA: 'BOX_NA',
  },

  BOX_STATUSES: {
    EMPTY_CLOSED: 'EMPTY_CLOSED',
    BOOKED: 'BOOKED',
    OCCUPIED_OPEN: 'OCCUPIED_OPEN',
    OCCUPIED_CLOSED: 'OCCUPIED_CLOSED',
    DISABLED: 'DISABLED',
    AWAITING_PAYMENT: 'AWAITING_PAYMENT',
    OPEN_REQUESTED: 'OPEN_REQUESTED',
    CANCEL_REQUESTED: 'CANCEL_REQUESTED',
    TERMINATE_REQUESTED: 'TERMINATE_REQUESTED',
    BLOCKED: 'BLOCKED',
  },

  TERMINAL_STATUSES: {
    ACTIVE: 'ACTIVE',
    SETUP_IN_PROGRESS: 'SETUP_IN_PROGRESS',
    DECOMMISSIONED: 'DECOMMISSIONED',
  },

  // PDF enum: FIVEBYFOUR = 5 columns x 4 rows = 20 boxes
  LAYOUT_TYPES: {
    FIVEBYFOUR: 'FIVEBYFOUR',
  },
  LAYOUT_DIMENSIONS: {
    FIVEBYFOUR: { rows: 4, cols: 5 },
  },

  ROW_LABELS: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
};
